#ifndef _SCHEDULING_LOAD_H
	#define _SCHEDULING_LOAD_H

#define CAPACITY_UPDATE_ADD		0x1
#define CAPACITY_UPDATE_SUBTRACT	0x2
#define CAPACITY_UPDATE_SET		0x3

#define LOAD_UPDATE_ADD			0x1
#define LOAD_UPDATE_SUBTRACT		0x2
#define LOAD_UPDATE_SET			0x3

#endif

