
#include <kernel/common/taskTrib/taskTrib.h>


taskTribC::taskTribC(void)
{
	prioClass[PRIOINDEX_REALTIME] = PRIOCLASS_REALTIME;
	prioClass[PRIOINDEX_IMPORTANT] = PRIOCLASS_IMPORTANT;
	prioClass[PRIOINDEX_FAST] = PRIOCLASS_FAST;
	prioClass[PRIOINDEX_NORMAL] = PRIOCLASS_NORMAL;
	prioClass[PRIOINDEX_DELAYABLE] = PRIOCLASS_DELAYABLE;
	prioClass[PRIOINDEX_NEGLIGABLE] = PRIOCLASS_NEGLIGABLE;
}

