
#include <kernel/common/taskTrib/taskTrib.h>


taskTribC::taskTribC(void)
{
	prioClass[PRIOINDEX_REALTIME] = PRIOCLASS_REALTIME;
	prioClass[PRIOINDEX_CRITICAL] = PRIOCLASS_CRITICAL;
	prioClass[PRIOINDEX_HIGH] = PRIOCLASS_HIGH;
	prioClass[PRIOINDEX_NORMAL] = PRIOCLASS_NORMAL;
	prioClass[PRIOINDEX_LOW] = PRIOCLASS_LOW;
	prioClass[PRIOINDEX_NEGLIGABLE] = PRIOCLASS_NEGLIGABLE;
}

