#ifndef _CHIPSET_DEDICATED_MEMORY_REGION_MAP_H
	#define _CHIPSET_DEDICATED_MEMORY_REGION_MAP_H

enum ChipsetDedicatedMemoryRegionsE
{
	CHIPSET_DEDICATED_MEMRGN_ISA_DMA = 0,
#ifdef CONFIG_ARCH_x86_32_PAE
	CHIPSET_DEDICATED_MEMRGN_x86_32_PAE_PDP,
#endif
	CHIPSET_DEDICATED_MEMRGN_NREGIONS
};

#endif /* _CHIPSET_DEDICATED_MEMORY_REGION_MAP_H */
