#ifndef _MEMORY_ALLOCATION_FLAGS_H
	#define _MEMORY_ALLOCATION_FLAGS_H

#define MEMALLOC_NO_FAKEMAP			
#define MEMALLOC_PURE_VIRTUAL			
#define MEMALLOC_NO_SLEEP			
#define MEMALLOC_NO_FLUSH_ALL			
#define MEMALLOC_NO_FLUSH_RESERVOIR		
#define MEMALLOC_NO_FLUSH_PTCACHE		
#define MEMALLOC_NO_FLUSH_BANK_CACHE		

#endif

