#!/bin/bash

export \
	CPP=$LCPP CC=$LCC CXX=$LCXX AS=$LAS LD=$LLD AR=$LAR \
	CPPFLAGS=$LCPPFLAGS \
	CCFLAGS=$LCCFLAGS \
	CXXFLAGS=$LCXXFLAGS \
	ASFLAGS=$LASFLAGS \
	LDFLAGS=$LLDFLAGS \
	ARFLAGS=$LARFLAGS

