#!/bin/bash

export \
	CPP=$ZCPP CC=$ZCC CXX=$ZCXX AS=$ZAS LD=$ZLD AR=$ZAR \
	CPPFLAGS=$ZCPPFLAGS \
	CCFLAGS=$ZCCFLAGS \
	CXXFLAGS=$ZCXXFLAGS \
	ASFLAGS=$ZASFLAGS \
	LDFLAGS=$ZLDFLAGS \
	ARFLAGS=$ZARFLAGS

