#ifndef _CONFIG_H
	#define _CONFIG_H

#define __ZAMBESII_KERNEL_SOURCE__
#define CONFIG_ARCH_x86_32
#define CONFIG_CHIPSET_IBM_PC
#define CONFIG_FIRMWARE_IBM_PC_BIOS
#define CONFIG_DTRIB_CISTERNN
#define CONFIG_DEBUG_LOCKS

#endif

